//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Access=
        ///Automount=TRUE
        ///Availability=
        ///BlockSize=4096
        ///BootVolume=FALSE
        ///
        ///
        ///Capacity=104853504
        ///Caption=\\?\Volume{e50d7cd1-0000-0000-0000-100000000000}\
        ///Compressed=FALSE
        ///ConfigManagerErrorCode=
        ///ConfigManagerUserConfig=
        ///CreationClassName=
        ///Description=
        ///DeviceID=\\?\Volume{e50d7cd1-0000-0000-0000-100000000000}\
        ///DirtyBitSet=FALSE
        ///DriveLetter=
        ///DriveType=3
        ///ErrorCleared=
        ///ErrorDescription=
        ///ErrorMethodology=
        ///FileSystem=NTFS
        ///FreeSpace=69255168
        ///IndexingEnabled=TRUE
        ///InstallDate=
        ///Label=Зарезервир [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WmiConsoleResult {
            get {
                return ResourceManager.GetString("WmiConsoleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///DeviceID=\\?\Volume{e50d7cd1-0000-0000-0000-100000000000}\
        ///
        ///
        ///DeviceID=\\?\Volume{e50d7cd1-0000-0000-0000-500600000000}\
        ///
        ///
        ///DeviceID=\\?\Volume{e50d7cd1-0000-0000-0000-106a18000000}\
        ///
        ///
        ///DeviceID=\\?\Volume{e50d7cd1-0000-0000-0000-d01d3b000000}\
        ///
        ///
        ///DeviceID=\\?\Volume{de76966d-2517-11e7-8209-806e6f6e6963}\
        ///
        ///
        ///.
        /// </summary>
        internal static string WmiConsoleResult_SingleProp {
            get {
                return ResourceManager.GetString("WmiConsoleResult_SingleProp", resourceCulture);
            }
        }
    }
}
