name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Print new build number
      run: echo "Build number is ${env:BUILD_NUMBER}"
    - uses: actions/checkout@v1
   # - name: Build with dotnet
   #   run: dotnet build --configuration Release
      
   # - name: Run Tests with dot net
   #   run: dotnet test
            
    - name: Build solution and generate NuGet package
      run: dotnet pack -c Release

    - name: Publis NuGet client
      run: dotnet nuget push WmiParser\bin\Release\*.nupkg -k  ${{secrets.NugetAPIKey}} -s https://www.nuget.org/
      
