name: .NET Core

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    
    - name: Generate build number
      uses: einaregilsson/build-number@v2
      id: buildnumber
      with:
        token: ${{secrets.github_token}}
      
    - uses: actions/checkout@v1
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Run Tests with dot net
      run: dotnet test
            
    - name: Build solution and generate NuGet package
      run: dotnet pack -c Release -p:PackageVersion=1.1.${{ steps.buildnumber.outputs.build_number }}

    - name: Publis NuGet client
      #run: dotnet nuget push WmiParser\bin\Release\*.nupkg -k  ${{secrets.NugetAPIKey}} -s https://www.nuget.org/
      
